name: Deploy MongoDB EC2 Instances

on:
  workflow_dispatch:
    inputs:
      instance_count:
        description: 'Number of EC2 Instances'
        required: true
        default: '1'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Update to your desired region

      - name: Launch EC2 instances with MongoDB setup
        run: |
          chmod +x launch_ec2.sh
          ./launch_ec2.sh ${{ github.event.inputs.instance_count }}
